apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: gannaloyik/zio-food-recipes:0.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: JDBC_DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: JDBC_DATABASE_URL
          ports:
            - containerPort: 9000