apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

patchesStrategicMerge:
  - api/update_service_type.yaml

images:
  - name: zio-food-recipes
    newName: ${ECR_REPOSITORY}
    newTag: ${IMAGE_TAG}
  - name: postgres
    newName: public.ecr.aws/docker/library/postgres
    newTag: latest
